const defaultBanner = 'Create Project Monorepo Template'
// let str=require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Create Project Monorepo Template').toString()
// console.log(str)
// const str2 = str.replace(/\u001b/g, '\\u001b');
// console.log(str2); 
// let fs=require("fs")
// fs.writeFile('example.txt', str2, (err) => {
//   if (err) throw err;
//   console.log('文件已保存');
// });

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Vue.js - The Progressive JavaScript Framework'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
  "\u001b[38;2;66;211;146mC\u001b[39m\u001b[38;2;66;211;146mr\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;66;211;146ma\u001b[39m\u001b[38;2;67;208;150mt\u001b[39m\u001b[38;2;69;204;155me\u001b[39m \u001b[38;2;70;201;159mP\u001b[39m\u001b[38;2;71;197;163mr\u001b[39m\u001b[38;2;73;194;168mo\u001b[39m\u001b[38;2;74;191;172mj\u001b[39m\u001b[38;2;76;187;177me\u001b[39m\u001b[38;2;77;184;181mc\u001b[39m\u001b[38;2;78;180;185mt\u001b[39m \u001b[38;2;80;177;190mM\u001b[39m\u001b[38;2;81;174;194mo\u001b[39m\u001b[38;2;82;170;198mn\u001b[39m\u001b[38;2;84;167;203mo\u001b[39m\u001b[38;2;85;163;207mr\u001b[39m\u001b[38;2;86;160;211me\u001b[39m\u001b[38;2;88;157;216mp\u001b[39m\u001b[38;2;89;153;220mo\u001b[39m \u001b[38;2;90;150;224mT\u001b[39m\u001b[38;2;92;146;229me\u001b[39m\u001b[38;2;93;143;233mm\u001b[39m\u001b[38;2;95;140;238mp\u001b[39m\u001b[38;2;96;136;242ml\u001b[39m\u001b[38;2;97;133;246ma\u001b[39m\u001b[38;2;99;129;251mt\u001b[39m\u001b[38;2;100;126;255me\u001b[39m"
// console.log('gradientBanner',gradientBanner)
export { defaultBanner, gradientBanner }
